apiVersion: v1
kind: Secret
metadata:
  name: ecr-registry-secret
type: Opaque
data:
  username: AWS
  password: eyJwYXlsb2FkIjoidGVxeDF4VjYvMjJTT3Fydzkrd2hMSGJDZFp5NnJEZ3AxUHdteTFSV2R3Zm81K1N3RFZvL3pPeE1LaE4ycUtjS1FmeGxDZ0dUb1NhNWJRQ0tQN3NNY0FXN0VxeDZJMGdraVU2UjBxY3pvN281YmlBb3FDb01NMXhPYk84Smhrc2hkcG9jVGxLM0ljck5WYklwYnlyQWpHRWZOek1lODV3NnJLN2JJeW4rd3pZQUJEdmRadE44dkUzbGgzbTYza1MrMmR5Rjdkd2JBYTZEbFlDTXRvdmVuL3FWY3BCMzVieXZkeVpObGRQQzE2ZTVIK0VMcjErb25kaDNSaWlpeTFYV1dtTTFwbXZTSFhSZzNyOGtEN3dOeGlSMmV3MkxneWJuMkRoYU1SK3JkQ0UrajdyWE03MXFnSkM5dDNZMm1xVXRYNWJoaG00azNsOHRmTkF3NHVmbk1WenU4bGlmTlQ0WTMxTHY2VXl0S2dScGNMWGdBaENwa2J2Z0tNV3Q2WktyQzdVbkxJZ2RQbExML2NYeUo1QzlOTmRYRDNVcWR1VmRtQ0RQSXR0MnZldFBoc1RMU2ZnQmV2YXlNbFpSTmJvMDQwb3ZTNFJDTXlIV2pJdFpoSnRnaFBySkFRQVdqMmFWTlkxVmhnbS9ZVHNNMGxCL3AxZjMzdE5RWGxNcnc5ZUZHUzJrOTFZbGhEeUpvWE43YmFRd0RHck5hYmtvbGFjL2ZiMEVRVXNXTXM2QTZMSWkvZWkxNGJFQzhTSU1BZk0vOWc5VGFqcjNua29adHhMYnhDUU5DdEVHZWNLbDJrRk40TjUrSlBFZkhRWkkzK3dld200RmZCL1JkaWtQYzRZOW92VGNLWllqc0t5eFUxV0NYNUJMSCtKNE1JSWNjKy9wSE84MkRWM1RSWG9MS0x4bDhPSzJnTXVVS1R5WFVPYUR4alVIVU1QNUIra3hhWmlnZEh6T08xQXhBQ245NE1Xc1FQa1N0bVZVYXhxdm9KQ3RIbE80c3FYVnhTL2JOQXdrUDNOOTdoV1hSa0tzNHAyQ0Q4bkFkclU3U05YcGZ2cUZ3TmQwWXgyWEkwRjFvNFVDYXVBZU1pbEIyRVc0ZlJpNk9qOWZ1aXpIelMrWXptREZtaVIxV0hvdk1iWmZ1ck92NlloeWU4dWpDU0ZYeUU5M01vWkxDQllteG5UNnVmU0xQL3NZUDdsQzdIK0pNYVVMQmI3b0pUcTV0QmJuZjY0WU4rRFBSV0ZlWWMzdTV0OUZNd1pyWDRlWjZlcDExbE9rRVdRcE9GZmp1UTMra0k0R2ZSV25XUWY1TnltbHU5enFwY05tTUxlTEJQWmhRNkxNandJbEFUTGZRMU9wIiwiZGF0YWtleSI6IkFRRUJBSGh3bTBZYUlTSmVSdEptNW4xRzZ1cWVla1h1b1hYUGU1VUZjZTlScTgvMTR3QUFBSDR3ZkFZSktvWklodmNOQVFjR29HOHdiUUlCQURCb0Jna3Foa2lHOXcwQkJ3RXdIZ1lKWUlaSUFXVURCQUV1TUJFRURQQk1SRTZRSXRwWTB3V2lQQUlCRUlBN0htS05DK3VsakVEdENFOEtVelNZRU84cDR1QmMwZU1TRkg4WmlBMWhENGtFYUw1aVYxejBqWnhZV2h6Ty9GL2M3VHZMc2JldktaNEF5M0E9IiwidmVyc2lvbiI6IjIiLCJ0eXBlIjoiREFUQV9LRVkiLCJleHBpcmF0aW9uIjoxNzA2ODMwMjUyfQ==
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hprofile
spec:
  selector:
    matchLabels:
      app: hprofile
  replicas: 2
  template:
    metadata:
      labels:
        app: hprofile
    spec:
      containers:
      - name: hprofile
        image: 339713042958.dkr.ecr.us-east-1.amazonaws.com/actapp:23
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: ecr-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: hprofile-service
spec:
  selector:
    app: hprofile
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort